### ISSUE TITLE
In another map, the minimap is just a gray box.

### ISSUE THREAD

**Issue by Orienser** [RimWorld-CCL-Reborn/BetterMiniMap#6]
More precisely speaking, if I load game in map A(my colony),the minimap is operating normally, then I switch over to the map B(my expedition team),minimap will look like this:
screenshot: https://ws1.sinaimg.cn/large/c9cae1c4gy1fnac36ffzuj209709075v.jpg

It look like doesn't clear the buffer before draw another thing,and doesn't draw another thing any more except the view box.

Sorry for my poor English.

**Comment by AaronCRobinson** [comment]
Hey Orienser,

Your English is fine. I have had this issue for awhile and thought it was just a lack of having enough memory. I eventually found the bug and it is fixed in the latest release that the github currently has and will be pushed to Steam when 1.0 is ready. Thanks for filing the issue. I will close this out but if you see it again after using the latest release, please feel free to re-open.
